name: stdlib module dependencies

on: 
    workflow_dispatch:
    repository_dispatch:
        types: [dependency-update]
    schedule:
        - cron: '30 18 * * *'
jobs:
    dependency:
        name: Derive module dependencies
        runs-on: ubuntu-latest
        steps:
            -   name : Configure GitHub
                env:
                    GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
                run: |
                    git config --global user.name ${{ secrets.BALLERINA_BOT_USERNAME }}
                    git config --global user.email ${{ secrets.BALLERINA_BOT_EMAIL }}
                    git clone https://${{ secrets.BALLERINA_BOT_USERNAME }}:${{ secrets.BALLERINA_BOT_TOKEN }}@github.com/ballerina-platform/ballerina-standard-library.git
                    cd ballerina-standard-library
        
            -   name: Setup Python
                uses: actions/setup-python@v2
                with:
                    python-version: '3.x'

            -   name: Install Python packages
                run: |
                    pip install requests
                    pip install networkx
                    pip install retry
            
            -   name: Get Dependencies and update files
                run: |
                    cd ballerina-standard-library
                    python release/src/module_dependencies/main.py
                env:
                    packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
                    packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
            
            -   name : Commit files
                env:
                    GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
                run: |
                    cd ballerina-standard-library
                    git update-index -q --refresh
                    if ! git diff-index --quiet HEAD --;then
                        git remote set-url origin https://${{ secrets.BALLERINA_BOT_USERNAME }}:${{ secrets.BALLERINA_BOT_TOKEN }}@github.com/ballerina-platform/ballerina-standard-library.git
                        git add .
                        git commit -m "stdlib_modules.json updated"
                        curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
                        bin/hub push origin main
                    else
                        echo "No changes to commit"
                    fi
