name: Update Stdlib Dependency Graph

on: 
    workflow_dispatch:
    schedule:
        -   cron: '30 8,20 * * *' # Run everyday at 8.30 AM and 8.30 PM
    push:
        branches:
          - main
        paths:
          - 'release/resources/module_list.json'

jobs:
    dependency:
        name: Derive module dependencies
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v2
        
            -   name: Setup Python
                uses: actions/setup-python@v2
                with:
                    python-version: '3.x'

            -   name: Install Python packages
                run: |
                    pip install requests
                    pip install networkx
                    pip install retry
                    pip install PyGithub
                    pip install semver
            
            -   name: Get Dependencies and update files
                run: |
                    python release/src/module_dependencies/update_version_data.py
                env:
                    packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
                    packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
            
            -   name : Commit files
                env:
                    GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
                run: |
                    git update-index -q --refresh
                    if ! git diff-index --quiet HEAD --;then
                        echo ::set-output name=changes::true
                        git remote set-url origin https://${{ secrets.BALLERINA_BOT_USERNAME }}:${{ secrets.BALLERINA_BOT_TOKEN }}@github.com/ballerina-platform/ballerina-standard-library.git
                        git add .
                        git commit -m "[Automated] Update the dependency order"
                        curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
                        bin/hub push origin main
                    else
                        echo "No changes to commit"
                    fi
